<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(NetTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\src-platform\KSW.Core\KSW.Core.csproj" />
    <ProjectReference Include="..\KSW.ATE01.Pattern.Domain.Projects.Core\KSW.ATE01.Pattern.Domain.Projects.Core.csproj" />
  </ItemGroup>

</Project>
