<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<TestplanType>Test-Plan</TestplanType>
		<RootNamespace>CustomerProgram</RootNamespace>
	</PropertyGroup>

	<Choose>
		<When Condition="'$(TestplanType)'=='Csv'">
			<ItemGroup>
				<EmbeddedResource Include="TestPlan\*.csv" />
			</ItemGroup>
		</When>
	</Choose>

	<ItemGroup>
	  <Compile Remove="Release\**" />
	  <EmbeddedResource Remove="Release\**" />
	  <None Remove="Release\**" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="KSW.ATE01.Instrument.IO">
	    <HintPath>D:\Src\KSW.ATE01.Platform\lib\KSW.ATE01.Instrument.IO\bin\Debug\net8.0\KSW.ATE01.Instrument.IO.dll</HintPath>
	  </Reference>
	  <Reference Include="KSW.ATE01.Project.Base">
	    <HintPath>D:\Src\KSW.ATE01.Platform\lib\KSW.ATE01.Instrument.IO\bin\Debug\net8.0\KSW.ATE01.Project.Base.dll</HintPath>
	  </Reference>
	</ItemGroup>

</Project>
