<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>CustomerProgram</RootNamespace>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Release\**" />
	  <EmbeddedResource Remove="Release\**" />
	  <None Remove="Release\**" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="KSW.ATE01.Instrument.IO">
	    <HintPath>D:\Src\KSW.ATE01.Platform\lib\KSW.ATE01.Instrument.IO\bin\Debug\net8.0-windows\KSW.ATE01.Instrument.IO.dll</HintPath>
	  </Reference>
	  <Reference Include="KSW.ATE01.Project.Base">
	    <HintPath>..\..\lib\KSW.ATE01.Project.Base\bin\Debug\net8.0-windows\KSW.ATE01.Project.Base.dll</HintPath>
	  </Reference>
	</ItemGroup>

</Project>
