<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(NetTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\KSW.ATE01.PPMU.Domain.Core\KSW.ATE01.PPMU.Domain.Core.csproj" />
  </ItemGroup>

</Project>
