//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSW.ATE01.Pattern.Start.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KSW.ATE01.Pattern.Start.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add Vector 的本地化字符串。
        /// </summary>
        internal static string AddVector {
            get {
                return ResourceManager.GetString("AddVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bin Folder 的本地化字符串。
        /// </summary>
        internal static string BinFolder {
            get {
                return ResourceManager.GetString("BinFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Channel Sheet 的本地化字符串。
        /// </summary>
        internal static string ChannelSheet {
            get {
                return ResourceManager.GetString("ChannelSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command 的本地化字符串。
        /// </summary>
        internal static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comment 的本地化字符串。
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compile 的本地化字符串。
        /// </summary>
        internal static string Compile {
            get {
                return ResourceManager.GetString("Compile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Vector 的本地化字符串。
        /// </summary>
        internal static string DeleteVector {
            get {
                return ResourceManager.GetString("DeleteVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export atp 的本地化字符串。
        /// </summary>
        internal static string ExportAtp {
            get {
                return ResourceManager.GetString("ExportAtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folder 的本地化字符串。
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Vector 的本地化字符串。
        /// </summary>
        internal static string InsertVector {
            get {
                return ResourceManager.GetString("InsertVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instrument 的本地化字符串。
        /// </summary>
        internal static string Instrument {
            get {
                return ResourceManager.GetString("Instrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Label 的本地化字符串。
        /// </summary>
        internal static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message 的本地化字符串。
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output 的本地化字符串。
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pattern Compiler 的本地化字符串。
        /// </summary>
        internal static string PatternCompiler {
            get {
                return ResourceManager.GetString("PatternCompiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pattern Editor 的本地化字符串。
        /// </summary>
        internal static string PatternEditor {
            get {
                return ResourceManager.GetString("PatternEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pattern File 的本地化字符串。
        /// </summary>
        internal static string PatternFile {
            get {
                return ResourceManager.GetString("PatternFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pin Overview 的本地化字符串。
        /// </summary>
        internal static string PinOverview {
            get {
                return ResourceManager.GetString("PinOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SaveAs 的本地化字符串。
        /// </summary>
        internal static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Plan 的本地化字符串。
        /// </summary>
        internal static string TestPlan {
            get {
                return ResourceManager.GetString("TestPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time 的本地化字符串。
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timing Name 的本地化字符串。
        /// </summary>
        internal static string TimingName {
            get {
                return ResourceManager.GetString("TimingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vector 的本地化字符串。
        /// </summary>
        internal static string Vector {
            get {
                return ResourceManager.GetString("Vector", resourceCulture);
            }
        }
    }
}
