//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSW.ATE01.Pattern.Start.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KSW.ATE01.Pattern.Start.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add Vector 的本地化字符串。
        /// </summary>
        internal static string AddVector {
            get {
                return ResourceManager.GetString("AddVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bin Folder 的本地化字符串。
        /// </summary>
        internal static string BinFolder {
            get {
                return ResourceManager.GetString("BinFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Channel Sheet 的本地化字符串。
        /// </summary>
        internal static string ChannelSheet {
            get {
                return ResourceManager.GetString("ChannelSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Command 的本地化字符串。
        /// </summary>
        internal static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comment 的本地化字符串。
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compile 的本地化字符串。
        /// </summary>
        internal static string Compile {
            get {
                return ResourceManager.GetString("Compile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect 的本地化字符串。
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Vector 的本地化字符串。
        /// </summary>
        internal static string DeleteVector {
            get {
                return ResourceManager.GetString("DeleteVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export atp 的本地化字符串。
        /// </summary>
        internal static string ExportAtp {
            get {
                return ResourceManager.GetString("ExportAtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file already exists, whether to overwrite it 的本地化字符串。
        /// </summary>
        internal static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Folder 的本地化字符串。
        /// </summary>
        internal static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Vector 的本地化字符串。
        /// </summary>
        internal static string InsertVector {
            get {
                return ResourceManager.GetString("InsertVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Instrument 的本地化字符串。
        /// </summary>
        internal static string Instrument {
            get {
                return ResourceManager.GetString("Instrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Label 的本地化字符串。
        /// </summary>
        internal static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message 的本地化字符串。
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open 的本地化字符串。
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output 的本地化字符串。
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error001: Can not find TimeSet info. Please check keyword &apos;import tset&apos; in atp file, And it must be &apos;;&apos; At the end. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr001 {
            get {
                return ResourceManager.GetString("PatternCompileErr001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error002：Can not find Pins info. Please check keyword &apos;$tset,&apos; in atp file,and use english &apos;,&apos; to separate elements. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr002 {
            get {
                return ResourceManager.GetString("PatternCompileErr002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error003: The TimingSet list contains the same name  的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr003 {
            get {
                return ResourceManager.GetString("PatternCompileErr003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error004：Unrecognized module type 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr004 {
            get {
                return ResourceManager.GetString("PatternCompileErr004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error005：Cannot recognize symbol &apos;{{&apos; and &apos;}}&apos; in the Instruments string &apos;{0}&apos;, cannot format it to Instrument object. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr005 {
            get {
                return ResourceManager.GetString("PatternCompileErr005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error006：No symbol &apos;}&apos; was found to match instruments module. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr006 {
            get {
                return ResourceManager.GetString("PatternCompileErr006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error007：The number of elements in the &apos;{0}&apos; in Instruments module is incorrec. Please check it. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr007 {
            get {
                return ResourceManager.GetString("PatternCompileErr007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error008：Unable to identify the Instrument Width value &apos;{0}&apos;, it should be the number. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr008 {
            get {
                return ResourceManager.GetString("PatternCompileErr008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error009：The Instrument Width ranges from 1 to 32. Current instrument width is {0}. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr009 {
            get {
                return ResourceManager.GetString("PatternCompileErr009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error010：Instrument width must be 1 when the Instrument mode is Parallel. Current instrument width is {0} 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr010 {
            get {
                return ResourceManager.GetString("PatternCompileErr010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 line {0} - error011：The number of pseudo instructions and parameters is greater than 2. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr011 {
            get {
                return ResourceManager.GetString("PatternCompileErr011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 line {0} - error012: Unrecognized label information {1}. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr012 {
            get {
                return ResourceManager.GetString("PatternCompileErr012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 line {0} - error013: Unrecognized label type {1}. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr013 {
            get {
                return ResourceManager.GetString("PatternCompileErr013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 line {0} - error014: Vector pins count is not match defined pins count in atp file. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr014 {
            get {
                return ResourceManager.GetString("PatternCompileErr014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 line {0} - error015: Undefined element &apos;{array[i].ToString()}&apos; in Vector. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr015 {
            get {
                return ResourceManager.GetString("PatternCompileErr015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 line {0} - error016: No parameter is allowed after PseudoInstruction &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr016 {
            get {
                return ResourceManager.GetString("PatternCompileErr016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 line {0} - error017: Undefined PseudoInstruction &apos;{1}&apos; in atp file. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr017 {
            get {
                return ResourceManager.GetString("PatternCompileErr017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 line {0} - error018: nonsupport PseudoInstruction {1}. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr018 {
            get {
                return ResourceManager.GetString("PatternCompileErr018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 line {0} - error019: The pseudoInstruction &apos;{1}&apos; must be followed by an argument. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr019 {
            get {
                return ResourceManager.GetString("PatternCompileErr019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 line {0} - error020: The number &apos;{1}&apos; after PseudoInstruction must be in the range of {2} to {3}. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr020 {
            get {
                return ResourceManager.GetString("PatternCompileErr020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 line {0} - error021: Content &apos;{1}&apos; after PseudoInstruction is not a valid value. It should be in the range {2} to {3} or in the list {4}. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr021 {
            get {
                return ResourceManager.GetString("PatternCompileErr021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 line {0} - error022: The pseudoInstruction &apos;{1}&apos; must be followed by an argument. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr022 {
            get {
                return ResourceManager.GetString("PatternCompileErr022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 line {0} - error023: The number &apos;{1}&apos; after PseudoInstruction &apos;{2}&apos; must be in the range of {3} to {4}. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr023 {
            get {
                return ResourceManager.GetString("PatternCompileErr023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 line {0} - error024: The number &apos;{1}&apos; after PseudoInstruction must be in the range of {3} to {4}. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr024 {
            get {
                return ResourceManager.GetString("PatternCompileErr024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 line {0} - error025: Undefined TimeSet &apos;{1}&apos; in atp file. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr025 {
            get {
                return ResourceManager.GetString("PatternCompileErr025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 line {0} - error026: Unrecognized PseudoInstruction parameter information &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr026 {
            get {
                return ResourceManager.GetString("PatternCompileErr026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 line {0} - error027: Unrecognized vector content. Cannot contain mutli pseudo. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr027 {
            get {
                return ResourceManager.GetString("PatternCompileErr027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 line {0} - error028: A single vector line cannot contain more than one label. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr028 {
            get {
                return ResourceManager.GetString("PatternCompileErr028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 error029: The vector row number in this atp file &apos;{0}&apos; is less than the minimum value &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr029 {
            get {
                return ResourceManager.GetString("PatternCompileErr029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 line {0} - error030: The number of pseudo instructions and parameters is greater than 2. Content is {1} 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr030 {
            get {
                return ResourceManager.GetString("PatternCompileErr030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 line {0} - error031: Comment should start with &apos;//&apos;. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr031 {
            get {
                return ResourceManager.GetString("PatternCompileErr031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 line {0} - error032: The V/D character appears in undefined Instrument. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr032 {
            get {
                return ResourceManager.GetString("PatternCompileErr032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 line {0} - warn033: The &apos;Start&apos; pseudoinstruction should not contain the &apos;D&apos; on the line. This row will be ignored and will not be counted in the number of rows containing D. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr033 {
            get {
                return ResourceManager.GetString("PatternCompileErr033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 line {0} - warn034: The &apos;Trig&apos; pseudoinstruction should not contain the &apos;V&apos; on the line. This row will be ignored and will not be counted in the number of rows containing V. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr034 {
            get {
                return ResourceManager.GetString("PatternCompileErr034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 line {0} - error035: Can&apos;t convert repeat parameter &apos;{1}&apos; to a number. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr035 {
            get {
                return ResourceManager.GetString("PatternCompileErr035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 line {0} - error036: Can&apos;t convert loop parameter &apos;{1}&apos; to a number. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr036 {
            get {
                return ResourceManager.GetString("PatternCompileErr036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 line {0} - error037: All pins in current instrument must be &apos;{1}&apos; at the same time. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileErr037 {
            get {
                return ResourceManager.GetString("PatternCompileErr037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Info001：&apos;instruments&apos; doesn&apos;t exist in atp. 的本地化字符串。
        /// </summary>
        internal static string PatternCompileInfo001 {
            get {
                return ResourceManager.GetString("PatternCompileInfo001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pattern Compiler 的本地化字符串。
        /// </summary>
        internal static string PatternCompiler {
            get {
                return ResourceManager.GetString("PatternCompiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pattern Editor 的本地化字符串。
        /// </summary>
        internal static string PatternEditor {
            get {
                return ResourceManager.GetString("PatternEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pattern File 的本地化字符串。
        /// </summary>
        internal static string PatternFile {
            get {
                return ResourceManager.GetString("PatternFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pin Overview 的本地化字符串。
        /// </summary>
        internal static string PinOverview {
            get {
                return ResourceManager.GetString("PinOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SaveAs 的本地化字符串。
        /// </summary>
        internal static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send 的本地化字符串。
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Plan 的本地化字符串。
        /// </summary>
        internal static string TestPlan {
            get {
                return ResourceManager.GetString("TestPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time 的本地化字符串。
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timing Name 的本地化字符串。
        /// </summary>
        internal static string TimingName {
            get {
                return ResourceManager.GetString("TimingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vector 的本地化字符串。
        /// </summary>
        internal static string Vector {
            get {
                return ResourceManager.GetString("Vector", resourceCulture);
            }
        }
    }
}
