<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(NetTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src-platform\KSW.Domain\KSW.Domain.csproj" />
    <ProjectReference Include="..\KSW.ATE01.Domain.Projects.Core\KSW.ATE01.Domain.Projects.Core.csproj" />
  </ItemGroup>

	<ItemGroup>
		<Compile Update="Entities/ProjectInfo.*.cs">
			<DependentUpon>ProjectInfo.cs</DependentUpon>
		</Compile>
	</ItemGroup>
</Project>
