//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KSW.ATE01.Start.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KSW.ATE01.Start.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About Us 的本地化字符串。
        /// </summary>
        internal static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Channel 的本地化字符串。
        /// </summary>
        internal static string AddChannel {
            get {
                return ResourceManager.GetString("AddChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add GroupName 的本地化字符串。
        /// </summary>
        internal static string AddGroupName {
            get {
                return ResourceManager.GetString("AddGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Level 的本地化字符串。
        /// </summary>
        internal static string AddLevel {
            get {
                return ResourceManager.GetString("AddLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add LevelGroup 的本地化字符串。
        /// </summary>
        internal static string AddLevelGroup {
            get {
                return ResourceManager.GetString("AddLevelGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Limit 的本地化字符串。
        /// </summary>
        internal static string AddLimit {
            get {
                return ResourceManager.GetString("AddLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Pin 的本地化字符串。
        /// </summary>
        internal static string AddPin {
            get {
                return ResourceManager.GetString("AddPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Timing 的本地化字符串。
        /// </summary>
        internal static string AddTiming {
            get {
                return ResourceManager.GetString("AddTiming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add TimingGroup 的本地化字符串。
        /// </summary>
        internal static string AddTimingGroup {
            get {
                return ResourceManager.GetString("AddTimingGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alert Highlight 的本地化字符串。
        /// </summary>
        internal static string AlertHighlight {
            get {
                return ResourceManager.GetString("AlertHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always on top 的本地化字符串。
        /// </summary>
        internal static string Always_on_top {
            get {
                return ResourceManager.GetString("Always on top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bookmarks 的本地化字符串。
        /// </summary>
        internal static string Bookmarks {
            get {
                return ResourceManager.GetString("Bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse 的本地化字符串。
        /// </summary>
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 can not be empty 的本地化字符串。
        /// </summary>
        internal static string CanNotBeEmpty {
            get {
                return ResourceManager.GetString("CanNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Channel Name 的本地化字符串。
        /// </summary>
        internal static string ChannelName {
            get {
                return ResourceManager.GetString("ChannelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Channel Setting 的本地化字符串。
        /// </summary>
        internal static string ChannelSetting {
            get {
                return ResourceManager.GetString("ChannelSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear All 的本地化字符串。
        /// </summary>
        internal static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Bookmarks 的本地化字符串。
        /// </summary>
        internal static string ClearBookmarks {
            get {
                return ResourceManager.GetString("ClearBookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comfirm SiteCount 的本地化字符串。
        /// </summary>
        internal static string ComfirmSiteCount {
            get {
                return ResourceManager.GetString("ComfirmSiteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Comment 的本地化字符串。
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration 的本地化字符串。
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure 的本地化字符串。
        /// </summary>
        internal static string Configure {
            get {
                return ResourceManager.GetString("Configure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure delete? 的本地化字符串。
        /// </summary>
        internal static string ConfirmTheDelete {
            get {
                return ResourceManager.GetString("ConfirmTheDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy as path 的本地化字符串。
        /// </summary>
        internal static string Copyaspath {
            get {
                return ResourceManager.GetString("Copyaspath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Project 的本地化字符串。
        /// </summary>
        internal static string CurrentProject {
            get {
                return ResourceManager.GetString("CurrentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Log 的本地化字符串。
        /// </summary>
        internal static string Datalog {
            get {
                return ResourceManager.GetString("Datalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date 的本地化字符串。
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delay Between Loops 的本地化字符串。
        /// </summary>
        internal static string DelayBetweenLoops {
            get {
                return ResourceManager.GetString("DelayBetweenLoops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Channel 的本地化字符串。
        /// </summary>
        internal static string DeleteChannel {
            get {
                return ResourceManager.GetString("DeleteChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete GroupName 的本地化字符串。
        /// </summary>
        internal static string DeleteGroupName {
            get {
                return ResourceManager.GetString("DeleteGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Limit 的本地化字符串。
        /// </summary>
        internal static string DeleteLimit {
            get {
                return ResourceManager.GetString("DeleteLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Pin 的本地化字符串。
        /// </summary>
        internal static string DeletePin {
            get {
                return ResourceManager.GetString("DeletePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Develop 的本地化字符串。
        /// </summary>
        internal static string Develop {
            get {
                return ResourceManager.GetString("Develop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dut Result 的本地化字符串。
        /// </summary>
        internal static string DutResult {
            get {
                return ResourceManager.GetString("DutResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Level 的本地化字符串。
        /// </summary>
        internal static string EditLevel {
            get {
                return ResourceManager.GetString("EditLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Limit 的本地化字符串。
        /// </summary>
        internal static string EditLimit {
            get {
                return ResourceManager.GetString("EditLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Pin 的本地化字符串。
        /// </summary>
        internal static string EditPin {
            get {
                return ResourceManager.GetString("EditPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Pin Group 的本地化字符串。
        /// </summary>
        internal static string EditPinGroup {
            get {
                return ResourceManager.GetString("EditPinGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Timing 的本地化字符串。
        /// </summary>
        internal static string EditTiming {
            get {
                return ResourceManager.GetString("EditTiming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End Test 的本地化字符串。
        /// </summary>
        internal static string EndTest {
            get {
                return ResourceManager.GetString("EndTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} more than {1} 的本地化字符串。
        /// </summary>
        internal static string ExceedValueError {
            get {
                return ResourceManager.GetString("ExceedValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Executable 的本地化字符串。
        /// </summary>
        internal static string Executable {
            get {
                return ResourceManager.GetString("Executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail Count 的本地化字符串。
        /// </summary>
        internal static string FailCount {
            get {
                return ResourceManager.GetString("FailCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail HardwareBin 的本地化字符串。
        /// </summary>
        internal static string FailHardwareBin {
            get {
                return ResourceManager.GetString("FailHardwareBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fail SoftwareBin 的本地化字符串。
        /// </summary>
        internal static string FailSoftwareBin {
            get {
                return ResourceManager.GetString("FailSoftwareBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} already exists 的本地化字符串。
        /// </summary>
        internal static string FieldAlreadyExists {
            get {
                return ResourceManager.GetString("FieldAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Field Is Required. 的本地化字符串。
        /// </summary>
        internal static string FieldIsRequired {
            get {
                return ResourceManager.GetString("FieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} have the same {1} value 的本地化字符串。
        /// </summary>
        internal static string FieldValueSame {
            get {
                return ResourceManager.GetString("FieldValueSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File 的本地化字符串。
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Change Check Interval 的本地化字符串。
        /// </summary>
        internal static string FileChangeCheckInterval {
            get {
                return ResourceManager.GetString("FileChangeCheckInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Copy Failed 的本地化字符串。
        /// </summary>
        internal static string FileCopyFailed {
            get {
                return ResourceManager.GetString("FileCopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File does not exist 的本地化字符串。
        /// </summary>
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Encoding 的本地化字符串。
        /// </summary>
        internal static string FileEncoding {
            get {
                return ResourceManager.GetString("FileEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Path 的本地化字符串。
        /// </summary>
        internal static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Reopen Check Interval 的本地化字符串。
        /// </summary>
        internal static string FileReopenCheckInterval {
            get {
                return ResourceManager.GetString("FileReopenCheckInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find 的本地化字符串。
        /// </summary>
        internal static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find Target 的本地化字符串。
        /// </summary>
        internal static string FindTarget {
            get {
                return ResourceManager.GetString("FindTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Goto Next Highlight 的本地化字符串。
        /// </summary>
        internal static string GotoNextHighlight {
            get {
                return ResourceManager.GetString("GotoNextHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Goto Previous Highlight 的本地化字符串。
        /// </summary>
        internal static string GotoPreviousHighlight {
            get {
                return ResourceManager.GetString("GotoPreviousHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group Name 的本地化字符串。
        /// </summary>
        internal static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group Setting 的本地化字符串。
        /// </summary>
        internal static string GroupSetting {
            get {
                return ResourceManager.GetString("GroupSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High Limit 的本地化字符串。
        /// </summary>
        internal static string HighLimit {
            get {
                return ResourceManager.GetString("HighLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Index 的本地化字符串。
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsDelete 的本地化字符串。
        /// </summary>
        internal static string IsDelete {
            get {
                return ResourceManager.GetString("IsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 is empty 的本地化字符串。
        /// </summary>
        internal static string IsEmpty {
            get {
                return ResourceManager.GetString("IsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keyword 的本地化字符串。
        /// </summary>
        internal static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keyword Highlight 的本地化字符串。
        /// </summary>
        internal static string KeywordHighlight {
            get {
                return ResourceManager.GetString("KeywordHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level GroupName 的本地化字符串。
        /// </summary>
        internal static string LevelGroupName {
            get {
                return ResourceManager.GetString("LevelGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Level Setting 的本地化字符串。
        /// </summary>
        internal static string LevelSetting {
            get {
                return ResourceManager.GetString("LevelSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Limit Name 的本地化字符串。
        /// </summary>
        internal static string LimitName {
            get {
                return ResourceManager.GetString("LimitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Limit Setting 的本地化字符串。
        /// </summary>
        internal static string LimitSetting {
            get {
                return ResourceManager.GetString("LimitSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The lower limit cannot exceed the upper limit 的本地化字符串。
        /// </summary>
        internal static string LimitValueError {
            get {
                return ResourceManager.GetString("LimitValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load Test Plan 的本地化字符串。
        /// </summary>
        internal static string LoadTestPlan {
            get {
                return ResourceManager.GetString("LoadTestPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log File 的本地化字符串。
        /// </summary>
        internal static string LogFile {
            get {
                return ResourceManager.GetString("LogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log Path 的本地化字符串。
        /// </summary>
        internal static string LogPath {
            get {
                return ResourceManager.GetString("LogPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loop Count 的本地化字符串。
        /// </summary>
        internal static string LoopCount {
            get {
                return ResourceManager.GetString("LoopCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Looping 的本地化字符串。
        /// </summary>
        internal static string Looping {
            get {
                return ResourceManager.GetString("Looping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loop Search 的本地化字符串。
        /// </summary>
        internal static string LoopSearch {
            get {
                return ResourceManager.GetString("LoopSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loops Executed 的本地化字符串。
        /// </summary>
        internal static string LoopsExecuted {
            get {
                return ResourceManager.GetString("LoopsExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Low Limit 的本地化字符串。
        /// </summary>
        internal static string LowLimit {
            get {
                return ResourceManager.GetString("LowLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No more matching keywords 的本地化字符串。
        /// </summary>
        internal static string MatchFailed {
            get {
                return ResourceManager.GetString("MatchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Left 的本地化字符串。
        /// </summary>
        internal static string MoveLeft {
            get {
                return ResourceManager.GetString("MoveLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move Right 的本地化字符串。
        /// </summary>
        internal static string MoveRight {
            get {
                return ResourceManager.GetString("MoveRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Project 的本地化字符串。
        /// </summary>
        internal static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Bookmark 的本地化字符串。
        /// </summary>
        internal static string NextBookmark {
            get {
                return ResourceManager.GetString("NextBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No site selected 的本地化字符串。
        /// </summary>
        internal static string NoSiteSelected {
            get {
                return ResourceManager.GetString("NoSiteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not found 的本地化字符串。
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not Saved 的本地化字符串。
        /// </summary>
        internal static string Notsaved {
            get {
                return ResourceManager.GetString("Notsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offline Mode 的本地化字符串。
        /// </summary>
        internal static string OfflineMode {
            get {
                return ResourceManager.GetString("OfflineMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open File 的本地化字符串。
        /// </summary>
        internal static string Open_File {
            get {
                return ResourceManager.GetString("Open File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Containing Folder 的本地化字符串。
        /// </summary>
        internal static string OpenContainingFolder {
            get {
                return ResourceManager.GetString("OpenContainingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Project 的本地化字符串。
        /// </summary>
        internal static string OpenProject {
            get {
                return ResourceManager.GetString("OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operate 的本地化字符串。
        /// </summary>
        internal static string Operate {
            get {
                return ResourceManager.GetString("Operate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation Successful 的本地化字符串。
        /// </summary>
        internal static string OperationSuccessful {
            get {
                return ResourceManager.GetString("OperationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Option 的本地化字符串。
        /// </summary>
        internal static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pass HardwareBin 的本地化字符串。
        /// </summary>
        internal static string PassHardwareBin {
            get {
                return ResourceManager.GetString("PassHardwareBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pass SoftwareBin 的本地化字符串。
        /// </summary>
        internal static string PassSoftwareBin {
            get {
                return ResourceManager.GetString("PassSoftwareBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pause Window 的本地化字符串。
        /// </summary>
        internal static string PauseWindow {
            get {
                return ResourceManager.GetString("PauseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Period 的本地化字符串。
        /// </summary>
        internal static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pin Name 的本地化字符串。
        /// </summary>
        internal static string PinName {
            get {
                return ResourceManager.GetString("PinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pin Or ProupName 的本地化字符串。
        /// </summary>
        internal static string PinOrGroupName {
            get {
                return ResourceManager.GetString("PinOrGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pin Type 的本地化字符串。
        /// </summary>
        internal static string PinType {
            get {
                return ResourceManager.GetString("PinType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please enter again 的本地化字符串。
        /// </summary>
        internal static string PleaseEnterAgain {
            get {
                return ResourceManager.GetString("PleaseEnterAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous Bookmark 的本地化字符串。
        /// </summary>
        internal static string PreviousBookmark {
            get {
                return ResourceManager.GetString("PreviousBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print Time 的本地化字符串。
        /// </summary>
        internal static string PrintTime {
            get {
                return ResourceManager.GetString("PrintTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project 的本地化字符串。
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project Created Failed 的本地化字符串。
        /// </summary>
        internal static string ProjectCreatedFailed {
            get {
                return ResourceManager.GetString("ProjectCreatedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project Created Successfully 的本地化字符串。
        /// </summary>
        internal static string ProjectCreatedSuccessfully {
            get {
                return ResourceManager.GetString("ProjectCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProjectDetail 的本地化字符串。
        /// </summary>
        internal static string ProjectDetail {
            get {
                return ResourceManager.GetString("ProjectDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project File 的本地化字符串。
        /// </summary>
        internal static string ProjectFile {
            get {
                return ResourceManager.GetString("ProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project Folder 的本地化字符串。
        /// </summary>
        internal static string ProjectFolder {
            get {
                return ResourceManager.GetString("ProjectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project Management 的本地化字符串。
        /// </summary>
        internal static string ProjectManagement {
            get {
                return ResourceManager.GetString("ProjectManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project Name 的本地化字符串。
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project Path 的本地化字符串。
        /// </summary>
        internal static string ProjectPath {
            get {
                return ResourceManager.GetString("ProjectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project Release To 的本地化字符串。
        /// </summary>
        internal static string ProjectReleaseTo {
            get {
                return ResourceManager.GetString("ProjectReleaseTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Publish Failed 的本地化字符串。
        /// </summary>
        internal static string PublishFailed {
            get {
                return ResourceManager.GetString("PublishFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RealTimeTxt 的本地化字符串。
        /// </summary>
        internal static string RealTimeTxt {
            get {
                return ResourceManager.GetString("RealTimeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Release 的本地化字符串。
        /// </summary>
        internal static string Release {
            get {
                return ResourceManager.GetString("Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reopen File 的本地化字符串。
        /// </summary>
        internal static string ReopenFile {
            get {
                return ResourceManager.GetString("ReopenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run 的本地化字符串。
        /// </summary>
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save As 的本地化字符串。
        /// </summary>
        internal static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save As Project Name 的本地化字符串。
        /// </summary>
        internal static string SaveAsName {
            get {
                return ResourceManager.GetString("SaveAsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save As Project Location 的本地化字符串。
        /// </summary>
        internal static string SaveAsPath {
            get {
                return ResourceManager.GetString("SaveAsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as file already exists 的本地化字符串。
        /// </summary>
        internal static string SaveAsPathExist {
            get {
                return ResourceManager.GetString("SaveAsPathExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as {0} cannot be the same as the source path 的本地化字符串。
        /// </summary>
        internal static string SaveAsPathSameError {
            get {
                return ResourceManager.GetString("SaveAsPathSameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Configure 的本地化字符串。
        /// </summary>
        internal static string SaveConfigure {
            get {
                return ResourceManager.GetString("SaveConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save TestPlan 的本地化字符串。
        /// </summary>
        internal static string SaveTestPlan {
            get {
                return ResourceManager.GetString("SaveTestPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Down 的本地化字符串。
        /// </summary>
        internal static string SearchDown {
            get {
                return ResourceManager.GetString("SearchDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Up 的本地化字符串。
        /// </summary>
        internal static string SearchUp {
            get {
                return ResourceManager.GetString("SearchUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Folder 的本地化字符串。
        /// </summary>
        internal static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Project 的本地化字符串。
        /// </summary>
        internal static string SelectProject {
            get {
                return ResourceManager.GetString("SelectProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Test Item 的本地化字符串。
        /// </summary>
        internal static string SetTestItem {
            get {
                return ResourceManager.GetString("SetTestItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Site 的本地化字符串。
        /// </summary>
        internal static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Site Information 的本地化字符串。
        /// </summary>
        internal static string SiteInformation {
            get {
                return ResourceManager.GetString("SiteInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Site Setting 的本地化字符串。
        /// </summary>
        internal static string SiteSetting {
            get {
                return ResourceManager.GetString("SiteSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Test 的本地化字符串。
        /// </summary>
        internal static string StartTest {
            get {
                return ResourceManager.GetString("StartTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop On Fail 的本地化字符串。
        /// </summary>
        internal static string StopOnFail {
            get {
                return ResourceManager.GetString("StopOnFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Template Installed Failed 的本地化字符串。
        /// </summary>
        internal static string TemplateInstalledFailed {
            get {
                return ResourceManager.GetString("TemplateInstalledFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Template Installed Successfully 的本地化字符串。
        /// </summary>
        internal static string TemplateInstalledSuccessfully {
            get {
                return ResourceManager.GetString("TemplateInstalledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Item 的本地化字符串。
        /// </summary>
        internal static string TestItem {
            get {
                return ResourceManager.GetString("TestItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Number 的本地化字符串。
        /// </summary>
        internal static string TestNumber {
            get {
                return ResourceManager.GetString("TestNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TestPlan 的本地化字符串。
        /// </summary>
        internal static string TestPlan {
            get {
                return ResourceManager.GetString("TestPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test Plan Type 的本地化字符串。
        /// </summary>
        internal static string TestPlanType {
            get {
                return ResourceManager.GetString("TestPlanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text Color 的本地化字符串。
        /// </summary>
        internal static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timing GroupName 的本地化字符串。
        /// </summary>
        internal static string TimingGroupName {
            get {
                return ResourceManager.GetString("TimingGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timing Name 的本地化字符串。
        /// </summary>
        internal static string TimingName {
            get {
                return ResourceManager.GetString("TimingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Timing Setting 的本地化字符串。
        /// </summary>
        internal static string TimingSetting {
            get {
                return ResourceManager.GetString("TimingSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle Bookmark 的本地化字符串。
        /// </summary>
        internal static string ToggleBookmark {
            get {
                return ResourceManager.GetString("ToggleBookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Units 的本地化字符串。
        /// </summary>
        internal static string Units {
            get {
                return ResourceManager.GetString("Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version 的本地化字符串。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Options 的本地化字符串。
        /// </summary>
        internal static string ViewOptions {
            get {
                return ResourceManager.GetString("ViewOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WaveformFormat 的本地化字符串。
        /// </summary>
        internal static string WaveformFormat {
            get {
                return ResourceManager.GetString("WaveformFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whole Word Match 的本地化字符串。
        /// </summary>
        internal static string WholeWordMatch {
            get {
                return ResourceManager.GetString("WholeWordMatch", resourceCulture);
            }
        }
    }
}
