<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(NetTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src-platform\KSW.Domain\KSW.Domain.csproj" />
    <ProjectReference Include="..\KSW.ATE01.Pattern.Domain.Instruments.Core\KSW.ATE01.Pattern.Domain.Instruments.Core.csproj" />
  </ItemGroup>

	<ItemGroup>
		<Compile Update="Entities/InstrumentInfo.*.cs">
			<DependentUpon>InstrumentInfo.cs</DependentUpon>
		</Compile>
	</ItemGroup>

</Project>
