// <auto-generated />
using KSW.ATE01.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KSW.ATE01.Sqlite.Migrations
{
    [DbContext(typeof(SystemUnitOfWork))]
    [Migration("20241022015141_20241022_0951")]
    partial class _20241022_0951
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");
#pragma warning restore 612, 618
        }
    }
}
