// <auto-generated />
using System;
using KSW.ATE01.Sqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KSW.ATE01.Sqlite.Migrations
{
    [DbContext(typeof(SystemUnitOfWork))]
    [Migration("20250819081607_20250819_1615")]
    partial class _20250819_1615
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("KSW.ATE01.Domain.Projects.Entities.ProjectInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("ProjectInfoId")
                        .HasComment("项目信息Id");

                    b.Property<DateTime?>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreationTime")
                        .HasComment("创建时间");

                    b.Property<string>("DatalogPath")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("DatalogPath")
                        .HasComment("日志路径");

                    b.Property<int?>("DelayBetweenLoops")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DelayBetweenLoops")
                        .HasComment("循环间时延");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsDeleted")
                        .HasComment("是否删除");

                    b.Property<bool?>("IsDoAll")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsDoAll")
                        .HasComment("是否DoAll");

                    b.Property<bool?>("IsPrintTime")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsPrintTime")
                        .HasComment("是否打印时间");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastModificationTime")
                        .HasComment("最后修改时间");

                    b.Property<int?>("LoopCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LoopCount")
                        .HasComment("循环次数");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("ProjectName")
                        .HasComment("项目名称");

                    b.Property<string>("ProjectPath")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("ProjectPath")
                        .HasComment("项目路径");

                    b.Property<string>("ProjectVersion")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("ProjectVersion")
                        .HasComment("项目版本");

                    b.Property<string>("ReleasePath")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("ReleasePath")
                        .HasComment("发布路径");

                    b.Property<bool?>("SaveCsv")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SaveCsv")
                        .HasComment("记录CSV");

                    b.Property<bool?>("SaveRealTimeText")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SaveRealTimeText")
                        .HasComment("记录RealTimeTxT");

                    b.Property<bool?>("SaveStdf")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SaveStdf")
                        .HasComment("记录STDF");

                    b.Property<bool?>("SaveSummary")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SaveSummary")
                        .HasComment("记录Summary");

                    b.Property<bool?>("StopOnFail")
                        .HasColumnType("INTEGER")
                        .HasColumnName("StopOnFail")
                        .HasComment("失败时停止");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("Version")
                        .HasComment("版本号");

                    b.HasKey("Id");

                    b.ToTable("ProjectInfo", null, t =>
                        {
                            t.HasComment("项目信息");
                        });
                });

            modelBuilder.Entity("KSW.ATE01.Domain.TestPlan.Entities.GlobalParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("GlobalParameterId")
                        .HasComment("全局参数Id");

                    b.Property<string>("AdditionInfo")
                        .HasColumnType("TEXT")
                        .HasColumnName("AdditionInfo")
                        .HasComment("附加信息");

                    b.Property<DateTime?>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreationTime")
                        .HasComment("创建时间");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsDeleted")
                        .HasComment("是否删除");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastModificationTime")
                        .HasComment("最后修改时间");

                    b.Property<string>("PatternFile")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("PatternFile")
                        .HasComment("向量文件名称");

                    b.Property<Guid>("ProjectInfoId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ProjectInfoId")
                        .HasComment("项目信息Id");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("Version")
                        .HasComment("版本号");

                    b.HasKey("Id");

                    b.ToTable("GlobalParameter", null, t =>
                        {
                            t.HasComment("全局参数");
                        });
                });

            modelBuilder.Entity("KSW.ATE01.Domain.TestPlan.Entities.GroupInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("GroupInfoId")
                        .HasComment("组信息Id");

                    b.Property<DateTime?>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreationTime")
                        .HasComment("创建时间");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("GroupName")
                        .HasComment("组名称");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsDeleted")
                        .HasComment("是否删除");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastModificationTime")
                        .HasComment("最后修改时间");

                    b.Property<Guid>("PinOverviewId")
                        .HasColumnType("TEXT")
                        .HasColumnName("PinOverviewId")
                        .HasComment("引脚总览Id");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("Version")
                        .HasComment("版本号");

                    b.HasKey("Id");

                    b.ToTable("GroupInfo", null, t =>
                        {
                            t.HasComment("组信息");
                        });
                });

            modelBuilder.Entity("KSW.ATE01.Domain.TestPlan.Entities.Level", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("LevelId")
                        .HasComment("测试项电平Id");

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("Comment")
                        .HasComment("注释");

                    b.Property<DateTime?>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreateTime")
                        .HasComment("创建时间");

                    b.Property<Guid?>("GroupOrPinId")
                        .HasColumnType("TEXT")
                        .HasColumnName("GroupOrPinId")
                        .HasComment("组或引脚Id");

                    b.Property<decimal?>("I")
                        .HasColumnType("TEXT")
                        .HasColumnName("I")
                        .HasComment("电流限制");

                    b.Property<decimal?>("Ioh")
                        .HasColumnType("TEXT")
                        .HasColumnName("Ioh")
                        .HasComment("高电平输出拉电流");

                    b.Property<decimal?>("Iol")
                        .HasColumnType("TEXT")
                        .HasColumnName("Iol")
                        .HasComment("低电平输出灌电流");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsDeleted")
                        .HasComment("是否删除");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastModificationTime")
                        .HasComment("最后修改时间");

                    b.Property<Guid>("LevelGroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("LevelGroupId")
                        .HasComment("测试项电平组Id");

                    b.Property<decimal?>("Ps")
                        .HasColumnType("TEXT")
                        .HasColumnName("Ps")
                        .HasComment("供电电压");

                    b.Property<int?>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Sequence")
                        .HasComment("上电顺序");

                    b.Property<int?>("Tdelay")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Tdelay")
                        .HasComment("上电延迟时间");

                    b.Property<decimal?>("Vch")
                        .HasColumnType("TEXT")
                        .HasColumnName("Vch")
                        .HasComment("错位高电压");

                    b.Property<decimal?>("Vcl")
                        .HasColumnType("TEXT")
                        .HasColumnName("Vcl")
                        .HasComment("错位低电压");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("Version")
                        .HasComment("版本号");

                    b.Property<decimal?>("Vih")
                        .HasColumnType("TEXT")
                        .HasColumnName("Vih")
                        .HasComment("输入高电压");

                    b.Property<decimal?>("Vil")
                        .HasColumnType("TEXT")
                        .HasColumnName("Vil")
                        .HasComment("输入低电压");

                    b.Property<decimal?>("Voh")
                        .HasColumnType("TEXT")
                        .HasColumnName("Voh")
                        .HasComment("输出高电压");

                    b.Property<decimal?>("Vol")
                        .HasColumnType("TEXT")
                        .HasColumnName("Vol")
                        .HasComment("输出低电压");

                    b.Property<decimal?>("Vt")
                        .HasColumnType("TEXT")
                        .HasColumnName("Vt")
                        .HasComment("电压基准");

                    b.HasKey("Id");

                    b.ToTable("Level", null, t =>
                        {
                            t.HasComment("测试项电平");
                        });
                });

            modelBuilder.Entity("KSW.ATE01.Domain.TestPlan.Entities.LevelGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("LevelGroupId")
                        .HasComment("测试项电平组Id");

                    b.Property<DateTime?>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreationTime")
                        .HasComment("创建时间");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsDeleted")
                        .HasComment("是否删除");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastModificationTime")
                        .HasComment("最后修改时间");

                    b.Property<string>("LevelGroupName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("LevelGroupName")
                        .HasComment("电平组名");

                    b.Property<Guid>("ProjectInfoId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ProjectInfoId")
                        .HasComment("项目信息Id");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("Version")
                        .HasComment("版本号");

                    b.HasKey("Id");

                    b.ToTable("LevelGroup", null, t =>
                        {
                            t.HasComment("测试项电平组");
                        });
                });

            modelBuilder.Entity("KSW.ATE01.Domain.TestPlan.Entities.Limits", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("LimitsId")
                        .HasComment("测试项门限Id");

                    b.Property<DateTime?>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreationTime")
                        .HasComment("创建时间");

                    b.Property<int?>("DutResult")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DutResult")
                        .HasComment("被测物结果");

                    b.Property<int?>("FailHardwareBin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FailHardwareBin")
                        .HasComment("硬件失效分档");

                    b.Property<int?>("FailSoftwareBin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FailSoftwareBin")
                        .HasComment("软件失效分档");

                    b.Property<decimal?>("HighLimit")
                        .HasColumnType("TEXT")
                        .HasColumnName("HighLimit")
                        .HasComment("电压上限");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsDeleted")
                        .HasComment("是否删除");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastModificationTime")
                        .HasComment("最后修改时间");

                    b.Property<string>("LimitName")
                        .HasColumnType("TEXT")
                        .HasColumnName("LimitName")
                        .HasComment("门限名称");

                    b.Property<decimal?>("LowLimit")
                        .HasColumnType("TEXT")
                        .HasColumnName("LowLimit")
                        .HasComment("电压下限");

                    b.Property<int?>("PassHardwareBin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PassHardwareBin")
                        .HasComment("硬件成功分档");

                    b.Property<int?>("PassSoftwareBin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PassSoftwareBin")
                        .HasComment("软件成功分档");

                    b.Property<Guid>("ProjectInfoId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ProjectInfoId")
                        .HasComment("项目信息Id");

                    b.Property<int>("TestNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TestNumber")
                        .HasComment("测试编号");

                    b.Property<string>("Units")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Units")
                        .HasComment("单位");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("Version")
                        .HasComment("版本号");

                    b.HasKey("Id");

                    b.ToTable("Limits", null, t =>
                        {
                            t.HasComment("测试项门限");
                        });
                });

            modelBuilder.Entity("KSW.ATE01.Domain.TestPlan.Entities.PinGroupRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("PinGroupRelationshipId")
                        .HasComment("引脚与组关系Id");

                    b.Property<DateTime?>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreationTime")
                        .HasComment("创建时间");

                    b.Property<Guid>("GroupInfoId")
                        .HasColumnType("TEXT")
                        .HasColumnName("GroupInfoId")
                        .HasComment("组信息Id");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastModificationTime")
                        .HasComment("最后修改时间");

                    b.Property<Guid>("PinInfoId")
                        .HasColumnType("TEXT")
                        .HasColumnName("PinInfoId")
                        .HasComment("引脚信息Id");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("Version")
                        .HasComment("版本号");

                    b.HasKey("Id");

                    b.ToTable("PinGroupRelationship", null, t =>
                        {
                            t.HasComment("引脚与组关系");
                        });
                });

            modelBuilder.Entity("KSW.ATE01.Domain.TestPlan.Entities.PinInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("PinInfoId")
                        .HasComment("引脚信息Id");

                    b.Property<DateTime?>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreationTime")
                        .HasComment("创建时间");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsDeleted")
                        .HasComment("是否删除");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastModificationTime")
                        .HasComment("最后修改时间");

                    b.Property<string>("PinName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("PinName")
                        .HasComment("引脚名称");

                    b.Property<Guid>("PinOverviewId")
                        .HasColumnType("TEXT")
                        .HasColumnName("PinOverviewId")
                        .HasComment("引脚总览Id");

                    b.Property<int?>("PinType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("PinType")
                        .HasComment("引脚类型");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("Version")
                        .HasComment("版本号");

                    b.HasKey("Id");

                    b.ToTable("PinInfo", null, t =>
                        {
                            t.HasComment("项目信息");
                        });
                });

            modelBuilder.Entity("KSW.ATE01.Domain.TestPlan.Entities.PinOverview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("PinOverview")
                        .HasComment("引脚总览Id");

                    b.Property<DateTime?>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreationTime")
                        .HasComment("创建时间");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsDeleted")
                        .HasComment("是否删除");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastModificationTime")
                        .HasComment("最后修改时间");

                    b.Property<Guid>("ProjectInfoId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ProjectInfoId")
                        .HasComment("项目信息Id");

                    b.Property<int?>("SiteCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SiteCount")
                        .HasComment("站点数");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("Version")
                        .HasComment("版本号");

                    b.HasKey("Id");

                    b.ToTable("PinOverview", null, t =>
                        {
                            t.HasComment("引脚总览");
                        });
                });

            modelBuilder.Entity("KSW.ATE01.Domain.TestPlan.Entities.PinSiteInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("PinSiteInfoId")
                        .HasComment("引脚站点信息Id");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("ChannelName")
                        .HasComment("通道名称");

                    b.Property<DateTime?>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreationTime")
                        .HasComment("创建时间");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastModificationTime")
                        .HasComment("最后修改时间");

                    b.Property<Guid>("PinInfoId")
                        .HasColumnType("TEXT")
                        .HasColumnName("PinInfoId")
                        .HasComment("引脚信息Id");

                    b.Property<Guid>("SiteInfoId")
                        .HasColumnType("TEXT")
                        .HasColumnName("SiteInfoId")
                        .HasComment("站点信息Id");

                    b.Property<int?>("SortId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SortId")
                        .HasComment("排序Id");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("Version")
                        .HasComment("版本号");

                    b.HasKey("Id");

                    b.ToTable("PinSiteInfo", null, t =>
                        {
                            t.HasComment("引脚站点信息");
                        });
                });

            modelBuilder.Entity("KSW.ATE01.Domain.TestPlan.Entities.SiteInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("SiteInfoId")
                        .HasComment("站点信息Id");

                    b.Property<DateTime?>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreationTime")
                        .HasComment("创建时间");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsDeleted")
                        .HasComment("是否删除");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastModificationTime")
                        .HasComment("最后修改时间");

                    b.Property<Guid>("PinOverviewId")
                        .HasColumnType("TEXT")
                        .HasColumnName("PinOverviewId")
                        .HasComment("引脚总览Id");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("SiteName")
                        .HasComment("站点名称");

                    b.Property<int>("SortId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SortId")
                        .HasComment("序号");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("Version")
                        .HasComment("版本号");

                    b.HasKey("Id");

                    b.ToTable("SiteInfo", null, t =>
                        {
                            t.HasComment("站点信息");
                        });
                });

            modelBuilder.Entity("KSW.ATE01.Domain.TestPlan.Entities.TestItemInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("TestItemInfoId")
                        .HasComment("测试项信息Id");

                    b.Property<string>("AdditionInfo")
                        .HasColumnType("TEXT")
                        .HasColumnName("AdditionInfo")
                        .HasComment("附加信息");

                    b.Property<DateTime?>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreationTime")
                        .HasComment("创建时间");

                    b.Property<decimal>("Force")
                        .HasColumnType("TEXT")
                        .HasColumnName("Force")
                        .HasComment("激励");

                    b.Property<string>("FunctionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("FunctionName")
                        .HasComment("方法名称");

                    b.Property<Guid?>("GroupOrPinId")
                        .HasColumnType("TEXT")
                        .HasColumnName("GroupOrPinId")
                        .HasComment("组或引脚Id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsDeleted")
                        .HasComment("是否删除");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastModificationTime")
                        .HasComment("最后修改时间");

                    b.Property<Guid?>("LevelGroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("LevelGroupId")
                        .HasComment("测试项电平组Id");

                    b.Property<Guid>("LimitsId")
                        .HasColumnType("TEXT")
                        .HasColumnName("LimitsId")
                        .HasComment("测试项门限Id");

                    b.Property<Guid>("ProjectInfoId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ProjectInfoId")
                        .HasComment("项目信息Id");

                    b.Property<string>("TestItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("TestItemName")
                        .HasComment("测试项名称");

                    b.Property<Guid?>("TimingGroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("TimingGroupId")
                        .HasComment("测试项时钟组Id");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("Version")
                        .HasComment("版本号");

                    b.HasKey("Id");

                    b.ToTable("TestItemInfo", null, t =>
                        {
                            t.HasComment("测试项信息");
                        });
                });

            modelBuilder.Entity("KSW.ATE01.Domain.TestPlan.Entities.Timing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("TimingId")
                        .HasComment("测试项时钟Id");

                    b.Property<DateTime?>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreationTime")
                        .HasComment("创建时间");

                    b.Property<int?>("DriveA")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DriveA")
                        .HasComment("环绕边缘");

                    b.Property<int?>("DriveB")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DriveB")
                        .HasComment("起始边缘");

                    b.Property<int?>("DriveC")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DriveC")
                        .HasComment("返回边缘");

                    b.Property<int?>("DriveD")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DriveD")
                        .HasComment("关闭边缘");

                    b.Property<Guid?>("GroupOrPinId")
                        .HasColumnType("TEXT")
                        .HasColumnName("GroupOrPinId")
                        .HasComment("组或引脚Id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsDeleted")
                        .HasComment("是否删除");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastModificationTime")
                        .HasComment("最后修改时间");

                    b.Property<int?>("Period")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Period")
                        .HasComment("周期");

                    b.Property<int?>("StrobeA")
                        .HasColumnType("INTEGER")
                        .HasColumnName("StrobeA")
                        .HasComment("选通开始时间");

                    b.Property<int?>("StrobeB")
                        .HasColumnType("INTEGER")
                        .HasColumnName("StrobeB")
                        .HasComment("选通结束时间");

                    b.Property<int?>("StrobeMode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("StrobeMode")
                        .HasComment("选通模式");

                    b.Property<Guid>("TimingGroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("TimingGroupId")
                        .HasComment("测试项时钟组Id");

                    b.Property<string>("TimingName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TimingName")
                        .HasComment("时钟名称");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("Version")
                        .HasComment("版本号");

                    b.Property<int?>("WaveformFormat")
                        .HasColumnType("INTEGER")
                        .HasColumnName("WaveformFormat")
                        .HasComment("波形格式");

                    b.HasKey("Id");

                    b.ToTable("Timing", null, t =>
                        {
                            t.HasComment("测试项时钟");
                        });
                });

            modelBuilder.Entity("KSW.ATE01.Domain.TestPlan.Entities.TimingGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("TimingGroupId")
                        .HasComment("测试项时钟组Id");

                    b.Property<DateTime?>("CreationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreationTime")
                        .HasComment("创建时间");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsDeleted")
                        .HasComment("是否删除");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("LastModificationTime")
                        .HasComment("最后修改时间");

                    b.Property<Guid>("ProjectInfoId")
                        .HasColumnType("TEXT")
                        .HasColumnName("ProjectInfoId")
                        .HasComment("项目信息Id");

                    b.Property<string>("TimingGroupName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("TimingGroupName")
                        .HasComment("时钟组名");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("Version")
                        .HasComment("版本号");

                    b.HasKey("Id");

                    b.ToTable("TimingGroup", null, t =>
                        {
                            t.HasComment("测试项时钟组");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
